import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>


        <ThemeContextProvider>
          <ThemeProvider>
            <AuthContextProvider>
              <div className="container">
                <div className="wrapper">
                  {/* Navbar  */}
                  {/* Navbar  */}
                  <Navbar />
                  {children}
                  <Footer />
                </div>

              </div>

            </AuthContextProvider>


          </ThemeProvider>


        </ThemeContextProvider>



      </body>



    </html>
  );
}
